language: python

sudo: false

python:
  - "2.7"
  - "3.6"

os:
  - linux

dist:
  - trusty

addons:
  apt:
    packages:
    - gfortran

branches:
  only:
    - master

install:
  - pip install numpy scipy nose
  - python setup.py build_ext --inplace

script: python -m nose -sv --with-coverage --cover-package=nice
