language: python

python:
  - "3.6"

os:
  - linux

dist:
  - trusty

addons:
  apt:
    packages:
    - gfortran

branches:
  only:
    - master

install:
  - pip install numpy scipy cma nose
  - python setup.py build_ext --inplace

script: python -m nose -v
